---
version: '3'
services:
  unifi:
    image: lscr.io/linuxserver/unifi-controller
    restart: always
    environment:
      - MEM_STARTUP=1024 #optional
      - MEM_LIMIT=1024 #optional
      - PUID=1000
      - PGID=1000
    ports:
      - 443:8443
      - 8080:8080
      - 3478:3478/udp
      - 10001:10001/udp
    volumes:
      - ./unifi:/config
